name: Manylinux Python wheels
on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: docker://mtgupf/essentia-builds:manylinux1_x86_64
        with:
          entrypoint: ls
          args: /github/workspace

